AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'config/**/*'
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
