version: '2'
services:
  rails: &app_base
    build:
      context: .
      dockerfile: 'Dockerfile.development'
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - "DATABASE_HOST=db"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    links:
      - db
    tty: true
    stdin_open: true
  spring:
    <<: *app_base
    command: "bundle exec spring server"
    ports: []
    tty: false
    stdin_open: false
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes_from:
      - data
    ports:
      - 3306:3306
  data:
    image: 'busybox'
    volumes:
      - '/var/lib/mysql'