default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['USEFUL_SHUFFLE_DATABASE_USERNAME'] %>
  password: <%= ENV['USEFUL_SHUFFLE_DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
 
development:
  <<: *default
  database: useful-shuffle_development
 
test:
  <<: *default
  database: useful-shuffle_test

production:
  <<: *default
  database: useful-shuffle_production
  username: <%= ENV['USEFUL_SHUFFLE_DATABASE_USERNAME'] %>
  password: <%= ENV['USEFUL_SHUFFLE_DATABASE_PASSWORD'] %>
